### ISSUE TITLE
HTTP 413 error in jupyterhub

### ISSUE THREAD

**Issue by machow** [cal-itp/data-infra#684]
* payload too large
* it sounds like this is happening when an output is too large (e.g. a graph, or a bunch of graphs?)
* I think there's probably a piece of config to raise this limit

edit: it sounds like we may need to (also?) tweak something with our cluster setup: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/1230#issuecomment-482318568

**Comment by holly-g** [comment]
May relate to #634

**Comment by lottspot** [comment]
@machow we have pushed the change we believe will help with this-- please have folks keep an eye out and report if this continues to be an issue!

**Comment by edasmalchi** [comment]
Thanks, this seems better!

I just tried stress testing it with a notebook that generates some big ipyleaflet maps -- saving was still possible with the first 2 map outputs displayed but with 3+ maps the HTTP 413 error reappears.

Not sure if it's possible to further increase the limit?

**Comment by holly-g** [comment]
@lottspot could we increase the limit?

**Comment by lottspot** [comment]
I think we're perfectly ok with bumping this limit up to 1GB. #894 stands as a reference for how to accomplish this.

**Comment by lottspot** [comment]
What we believe to be a related report has come in from @amandaha8 regarding this issue:

> Hi, just wanted to flag this in jupyterhub. My notebook is failing to save even though I only have 2 bar charts in my output. I have a pop up that says "file save error for notebook valid response 4313".
<img width="539" alt="filesave" src="https://user-images.githubusercontent.com/2199417/153407448-bac5999a-784d-495d-bbc2-fa9c46472b55.PNG">

**Comment by Nkdiaz** [comment]
This was solved by linked pull request

**Comment by Nkdiaz** [comment]
On 03/04/22 some of the analysists reported that they still see the 413 error.  @natam1. @edasmalchi, and @amandaha8 have all reported 413 errors when trying to save in jupyterhub in the past week. According to @atvaccaro , when the analysts download the WIP notebook, refresh the page, and upload the notebook again it is able to save again. This involved a token that is given on page load so reloading the page usually forces the re-auth and a new token. One potential way forward would be to enable auto-save so that you lose less work if you are unable to save manually.

**Comment by atvaccaro** [comment]
> According to @atvaccaro , when the analysts download the WIP notebook, refresh the page, and upload the notebook again it is able to save again. This involved a token that is given on page load so reloading the page usually forces the re-auth and a new token. One potential way forward would be to enable auto-save so that you lose less work if you are unable to save manually.

Just to clarify, this was in reference to a CSRF token issue, not nginx 413 errors.

@lauriemerrell said a couple analysts were still seeing errors, so I have a [new PR ](https://github.com/cal-itp/data-infra/pull/1245)to explicitly set 1g as the limit rather than 0.
